version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    ports:
      - "8089:8089"
    depends_on:
      - db
      - zookeeper
  db:
    image: postgres
    environment:
      POSTGRES_DB: movie_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"